2020-12-12 22:09:11,422   INFO     server.py : "Установлено соединение с клиетном: ('127.0.0.1', 59002)"
2020-12-12 22:09:12,009   ERROR    server.py : "Получены некоретные данные от клиента ('127.0.0.1', 59002). Соединение разорвано"
2020-12-12 22:09:29,002   INFO     server.py : "Установлено соединение с клиетном: ('127.0.0.1', 59018)"
2020-12-12 22:09:29,033   INFO     server.py : "Получено сообщение от клиента: {'action': 'presence', 'time': 1607782169.004386, 'user': {'account_name': 'Guest'}}"
2020-12-12 22:09:29,033   DEBUG    server.py : "Получено сообщение {'action': 'presence', 'time': 1607782169.004386, 'user': {'account_name': 'Guest'}} от клиента Guest"
2020-12-12 22:09:29,034   DEBUG    server.py : "Отправлен ответ {'response': 200} клиенту Guest"
2020-12-12 22:09:29,034   DEBUG    server.py : "Сформирован ответ клиенту: {'response': 200}"
2020-12-12 22:09:29,034   INFO     server.py : "Отправлено сообщение {'response': 200} клиенту ('127.0.0.1', 59018)"
2020-12-12 22:09:29,034   INFO     server.py : "Соединение с клиентом разорвано"
2020-12-12 22:11:26,875   INFO     server.py : "Установлено соединение с клиетном: ('127.0.0.1', 59078)"
2020-12-12 22:11:26,893   INFO     server.py : "Получено сообщение от клиента: {'action': 'presence', 'time': 1607782286.8755352, 'user': {'account_name': 'Guest'}}"
2020-12-12 22:11:26,893   DEBUG    server.py : "Получено сообщение {'action': 'presence', 'time': 1607782286.8755352, 'user': {'account_name': 'Guest'}} от клиента Guest"
2020-12-12 22:11:26,894   DEBUG    server.py : "Отправлен ответ {'response': 200} клиенту Guest"
2020-12-12 22:11:26,894   DEBUG    server.py : "Сформирован ответ клиенту: {'response': 200}"
2020-12-12 22:11:26,894   INFO     server.py : "Отправлено сообщение {'response': 200} клиенту ('127.0.0.1', 59078)"
2020-12-12 22:11:26,895   INFO     server.py : "Соединение с клиентом разорвано"
2020-12-12 22:13:38,328   INFO     server.py : "Установлено соединение с клиетном: ('127.0.0.1', 59118)"
2020-12-12 22:13:38,352   INFO     server.py : "Получено сообщение от клиента: {'action': 'presence', 'time': 1607782418.3290489, 'user': {'account_name': 'Guest'}}"
2020-12-12 22:13:38,353   DEBUG    server.py : "Получено сообщение {'action': 'presence', 'time': 1607782418.3290489, 'user': {'account_name': 'Guest'}} от клиента Guest"
2020-12-12 22:13:38,353   DEBUG    server.py : "Отправлен ответ {'response': 200} клиенту Guest"
2020-12-12 22:13:38,353   DEBUG    server.py : "Сформирован ответ клиенту: {'response': 200}"
2020-12-12 22:13:38,354   INFO     server.py : "Отправлено сообщение {'response': 200} клиенту ('127.0.0.1', 59118)"
2020-12-12 22:13:38,354   INFO     server.py : "Соединение с клиентом разорвано"
2020-12-12 22:21:09,039   INFO     server.py : "Установлено соединение с клиетном: ('127.0.0.1', 59364)"
2020-12-12 22:21:09,429   ERROR    server.py : "Получены некоретные данные от клиента ('127.0.0.1', 59364). Соединение разорвано"
2020-12-12 22:21:16,403   INFO     server.py : "Установлено соединение с клиетном: ('127.0.0.1', 59366)"
2020-12-12 22:21:16,785   ERROR    server.py : "Получены некоретные данные от клиента ('127.0.0.1', 59366). Соединение разорвано"
2020-12-12 22:21:25,697   INFO     server.py : "Установлено соединение с клиетном: ('127.0.0.1', 59370)"
2020-12-12 22:21:26,195   ERROR    server.py : "Получены некоретные данные от клиента ('127.0.0.1', 59370). Соединение разорвано"
2020-12-12 22:22:36,878   INFO     server.py : "Установлено соединение с клиетном: ('127.0.0.1', 59386)"
2020-12-12 22:22:37,305   ERROR    server.py : "Получены некоретные данные от клиента ('127.0.0.1', 59386). Соединение разорвано"
2020-12-12 22:22:57,530   INFO     server.py : "Установлено соединение с клиетном: ('127.0.0.1', 59392)"
2020-12-12 22:22:57,546   INFO     server.py : "Получено сообщение от клиента: {'action': 'presence', 'time': 1607782977.5303485, 'user': {'account_name': 'Guest'}}"
2020-12-12 22:22:57,547   DEBUG    server.py : "Получено сообщение {'action': 'presence', 'time': 1607782977.5303485, 'user': {'account_name': 'Guest'}} от клиента Guest"
2020-12-12 22:22:57,547   DEBUG    server.py : "Отправлен ответ {'response': 200} клиенту Guest"
2020-12-12 22:22:57,547   DEBUG    server.py : "Сформирован ответ клиенту: {'response': 200}"
2020-12-12 22:22:57,547   INFO     server.py : "Отправлено сообщение {'response': 200} клиенту ('127.0.0.1', 59392)"
2020-12-12 22:22:57,548   INFO     server.py : "Соединение с клиентом разорвано"
2020-12-12 22:24:26,180   INFO     server.py : "Установлено соединение с клиетном: ('127.0.0.1', 59412)"
2020-12-12 22:24:26,197   INFO     server.py : "Получено сообщение от клиента: {'action': 'presence', 'time': 1607783066.181134, 'user': {'account_name': 'Guest'}}"
2020-12-12 22:24:26,198   DEBUG    server.py : "Получено сообщение {'action': 'presence', 'time': 1607783066.181134, 'user': {'account_name': 'Guest'}} от клиента Guest"
2020-12-12 22:24:26,198   DEBUG    server.py : "Отправлен ответ {'response': 200} клиенту Guest"
2020-12-12 22:24:26,213   DEBUG    server.py : "Вызвана функция get_response_for_message с параметрами ({'action': 'presence', 'time': 1607783066.181134, 'user': {'account_name': 'Guest'}},) и {}. Модуль функции: __main__. Вызов из функции main"
2020-12-12 22:24:26,213   DEBUG    server.py : "Сформирован ответ клиенту: {'response': 200}"
2020-12-12 22:24:26,213   INFO     server.py : "Отправлено сообщение {'response': 200} клиенту ('127.0.0.1', 59412)"
2020-12-12 22:24:26,214   INFO     server.py : "Соединение с клиентом разорвано"
2020-12-12 22:25:42,345   INFO     server.py : "Установлено соединение с клиетном: ('127.0.0.1', 59430)"
2020-12-12 22:25:42,362   INFO     server.py : "Получено сообщение от клиента: {'action': 'presence', 'time': 1607783142.3456936, 'user': {'account_name': 'Guest'}}"
2020-12-12 22:25:42,362   DEBUG    server.py : "Получено сообщение {'action': 'presence', 'time': 1607783142.3456936, 'user': {'account_name': 'Guest'}} от клиента Guest"
2020-12-12 22:25:42,362   DEBUG    server.py : "Отправлен ответ {'response': 200} клиенту Guest"
2020-12-12 22:25:42,379   DEBUG    server.py : "Вызвана функция get_response_for_message с параметрами ({'action': 'presence', 'time': 1607783142.3456936, 'user': {'account_name': 'Guest'}},) и {}. Модуль функции: __main__. Вызов из функции main"
2020-12-12 22:25:42,379   DEBUG    server.py : "Сформирован ответ клиенту: {'response': 200}"
2020-12-12 22:25:42,379   INFO     server.py : "Отправлено сообщение {'response': 200} клиенту ('127.0.0.1', 59430)"
2020-12-12 22:25:42,380   INFO     server.py : "Соединение с клиентом разорвано"
2020-12-15 09:55:31,831   INFO     server.py : "Установлено соединение с клиетном: ('127.0.0.1', 54807)"
2020-12-15 09:55:31,929   INFO     server.py : "Получено сообщение от клиента: {'action': 'presence', 'time': 1607997331.8338656, 'user': {'account_name': 'Guest'}}"
2020-12-15 09:55:31,929   DEBUG    server.py : "Получено сообщение {'action': 'presence', 'time': 1607997331.8338656, 'user': {'account_name': 'Guest'}} от клиента Guest"
2020-12-15 09:55:31,930   DEBUG    server.py : "Отправлен ответ {'response': 200} клиенту Guest"
2020-12-15 09:55:32,017   DEBUG    server.py : "Вызвана функция get_response_for_message с параметрами ({'action': 'presence', 'time': 1607997331.8338656, 'user': {'account_name': 'Guest'}},) и {}. Модуль функции: __main__. Вызов из функции main"
2020-12-15 09:55:32,018   DEBUG    server.py : "Сформирован ответ клиенту: {'response': 200}"
2020-12-15 09:55:32,019   INFO     server.py : "Отправлено сообщение {'response': 200} клиенту ('127.0.0.1', 54807)"
2020-12-15 09:55:32,020   INFO     server.py : "Соединение с клиентом разорвано"
